# Site settings
title: "Dossier Contente"
email: 
description: "A realidade é vestida e bem passada"
baseurl: "/contente"
url: "http://fiat-justitia.github.io/"

title_description: "A realidade é vestida e bem passada"
title_image: "https://upload.wikimedia.org/wikipedia/commons/9/9d/Drew_family_crest.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: 
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs


# Footer
footer_left: ""
footer_right: ""

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
